archiveHL7Application:Архивска HL7 апликација|Информације повезане са DICOM архивском HL7 апликацијом
archiveHL7Application.dicomAETitle:AE наслов|Archive AE Title повезан са овом HL7 апликацијом.
archiveHL7Application.dcmRecordAttributeModification:Бележи измене атрибута|Указује да ли се измене атрибута ускладиштених објеката ове HL7 апликације записују у ставкама Original Attributes Sequence. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.dcmMWLWorklistLabel:MWL ознака Worklist-е|Вредност Worklist Label (0074,1202) креираних MWL ставки при пријему HL7 Order порука. Ако није наведено, креиране MWL ставке нису везане за појединачни MWL Worklist и пружају их сви Арцхиве AE са MWL SCP Transfer Capability.
archiveHL7Application.dcmMWLAccessionNumberGenerator:Генератор приступног броја MWL|Идентификује ID Generator за допуну недостајућих Accession Numbers Scheduled Procedures Steps креираних при пријему HL7 Order порука. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.dcmMWLRequestedProcedureIDGenerator:Генератор ID-а траженог поступка MWL|Идентификује ID Generator за допуну недостајућих Requested Procedure IDs Scheduled Procedures Steps креираних при пријему HL7 Order порука. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.dcmMWLScheduledProcedureStepIDGenerator:Генератор ID-а заказаног корака процедуре MWL|Идентификује ID Generator за допуну недостајућих Scheduled Procedure Step IDs Scheduled Procedures Steps креираних при пријему HL7 Order порука. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.dcmAuditHL7MsgLimit:Лимит HL7 порука ревизије|Ограничи дужину HL7 порука укључених у емитоване Audit Records. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ORUAction:HL7 ORU акција|Специфицира акцију при пријему HL7 ORU^R01 поруке. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ORUAction.IMPORT_REPORT:Transcode received HL7 ORU^R01 to DICOM SR or PDF or CDA
archiveHL7Application.hl7ORUAction.MWL_COMPLETED:Set Status of matching MWL items to COMPLETED
archiveHL7Application.hl7PatientUpdateTemplateURI:URI шаблона HL7 ажурирања пацијента|Специфицира URI style схеет-а који користи HL7v2 Patient Update услуга. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ImportReportTemplateURI:URI шаблона HL7 увоза извештаја|Специфицира URI style схеет-а за транскодирање примљених HL7 ORU^R01 у DICOM SR. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ImportReportTemplateParam:Параметар шаблона HL7 увоза извештаја|XSLT параметри прослеђени style схеет-у наведеном у HL7 Import Report Template URI. Формат: {name}={value}. Нпр.: 'langCodeValue=et', 'langCodingSchemeDesignator=RFC5646', 'langCodeMeaning=Estonian'. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ScheduleProcedureTemplateURI:URI шаблона HL7 заказивања поступка|Специфицира URI style схеет-а за транскодирање примљених HL7 ORM^O01, OMI^O23, OMG^O19 у DICOM MWL ставке. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ScheduledProtocolCodeInOrder:HL7 код протокола заказивања у налогу|Специфицира локацију Scheduled Protocol Code у примљеној HL7 Order поруци. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ScheduledProtocolCodeInOrder.OBR_4_1:HL7 Schedule Protocol Code in Order in OBR.4.1 to OBR.4.3
archiveHL7Application.hl7ScheduledProtocolCodeInOrder.OBR_4_4:HL7 Schedule Protocol Code in Order in OBR.4.4 to OBR.4.6
archiveHL7Application.hl7ScheduledStationAETInOrder:HL7 AET станице заказивања у налогу|Специфицира локацију Scheduled Station AE Title у примљеној HL7 Order поруци. Не би требало конфигурисати за HL7 в2.5.1 OMI^O23 са IPC сегментом. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ScheduledStationAETInOrder.ORC_18:HL7 Schedule Station AET in Order in ORC.18
archiveHL7Application.hl7LogFilePattern:Образац HL7 log фајла|Путања до HL7 порука које ће бити снимљене тачно онако како су примљене. Ако није наведено, нема логовања. Преписује вредност наведену на нивоу уређаја. нпр. ${jboss.server.data.dir}/хл7/${date,yyyy/MM/dd}/${SerialNo}-${MSH-9}.хл7
archiveHL7Application.hl7ErrorLogFilePattern:Образац HL7 лог фајла грешака|Путања до HL7 порука које ће бити снимљене тачно онако како су примљене, када обрада HL7 порука не успе. Ако није наведено, нема логовања. Преписује вредност наведену на нивоу уређаја. нпр. ${jboss.server.data.dir}/хл7-еррор/${date,yyyy/MM/dd}/${SerialNo}-${MSH-9}.хл7
archiveHL7Application.hl7OutgoingLogFilePattern:Образац HL7 одлазног лог фајла|Путања до HL7 порука које ће бити снимљене тачно онако како су послате. Ако није наведено, нема логовања. Може бити преписано конфигурисаним вредностима за поједине Archive HL7 Application. нпр. ${jboss.server.data.dir}/хл7-оут/${date,yyyy/MM/dd}/${SerialNo}-${MSH-9}.хл7
archiveHL7Application.hl7OutgoingErrorLogFilePattern:Образац HL7 одлазног лог фајла грешака|Путања до HL7 порука које ће бити снимљене тачно онако како су послате, када обрада послатих HL7 порука не успе. Ако није наведено, нема логовања. Може бити преписано конфигурисаним вредностима за поједине Archive HL7 Application. нпр. ${jboss.server.data.dir}/хл7-оут-еррор/${date,yyyy/MM/dd}/${SerialNo}-${MSH-9}.хл7
archiveHL7Application.hl7NoPatientCreateMessageType:HL7 тип поруке о непостојању креирања пацијента|Тип(ови) поруке (MessageType^TriggerEvent) HL7 порука које се обрађују само ако већ постоји запис пацијента у бази података чији Patient ID одговара Patient ID-у у PID или MRG сегменту поруке. Дакле неће бити креиран нови запис пацијента порукама наведених типова. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7NoPatientUpdateMessageType:HL7 тип поруке о непостојању ажурирања пацијента|Запис пацијента се неће ажурирати HL7 порукама наведеног типа поруке (MessageType^TriggerEvent). Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7PatientArrivalMessageType:HL7 тип поруке о доласку пацијента|Message Type HL7 порука које покрећу промену статуса Scheduled Procedure Steps повезаних са Patient из SCHEDULED у ARRIVED. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7PatientArrivalMessageType.ADT^A10:Patient Arriving / Tracking
archiveHL7Application.hl7UseNullValue:Користи HL7 null вредност|Специфицира да ли се HL7 в2 null вредности (специфициране у пољу сегмента као |""|) користе у послатим HL7 порукама за непостојеће или празне атрибуте ентитета. Потребно за поништавање атрибута ентитета код удаљене HL7 апликације. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7VeterinaryUsePatientName:HL7 ветеринарско коришћење имена пацијента|Указује на присилно ветеринарско коришћење Patient Names при мапирању HL7 PID поља у DICOM атрибуте: користи само прве две компоненте PID.5 као DICOM Patient Name; ако PID.5 садржи само једну компоненту, користи ту вредност као гивен наме, а прву компоненту PID.9 као family наме DICOM Patient Name. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7PrimaryAssigningAuthorityOfPatientID:HL7 примарни издавалац ауторитета ID-а пацијента|Assigning Authority Patient ID-а у примљеној HL7 поруци коришћен за претрагу примарног квалификованог идентификатора пацијента у листи идентификатора у PID-3 / MRG.1. Овај квалификовани идентификатор пацијента се користи на роот датасет-у. Ако није наведено, подразумевано се први пар идентификатора пацијента у PID-3 / MRG.1 користи као примарни идентификатор пацијента на роот датасет-у. Ако ниједан од квалификованих идентификатора пацијента у листи не одговара конфигурисаном иссуер-у, лог архиве сервера ће садржати лог INFO поруку и подразумевано ће се користити први квалификовани идентификатор пацијента у PID-3 / MRG.1. Формат: {Issuer of Patient ID}[&{UniversalEntityID}&{UniversalEntityIDType}]. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7OtherPatientIDs:HL7 остали ID-ови пацијената|Специфицира политику укључивања идентификатора пацијента у PID-3 / MRG-1 HL7 поруке у Other Patient IDs Sequence (0010,1002). Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7OtherPatientIDs.ALL:Include all patient identifiers in PID.3 / MRG.1, including patient identifier on root dataset in Other Patient IDs Sequence (0010,1002)
archiveHL7Application.hl7OtherPatientIDs.NONE:Include no patient identifiers from PID.3 / MRG.1 in Other Patient IDs Sequence (0010,1002)
archiveHL7Application.hl7OtherPatientIDs.OTHER:Include all patient identifiers in PID.3 / MRG.1, except patient identifier on root dataset in Other Patient IDs Sequence (0010,1002)
archiveHL7Application.hl7OrderMissingStudyIUIDPolicy:Политика HL7 налога без Study Instance UID-а|Специфицира политику за недостајући Study Instance UID у долазним HL7 Order порукама. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7OrderMissingStudyIUIDPolicy.REJECT:Reject HL7 Order Messages with missing Study Instance UID in ZDS.1 / IPC.3
archiveHL7Application.hl7OrderMissingStudyIUIDPolicy.GENERATE:Generate random Study Instance UID if missing in HL7 Order Messages in ZDS.1 / IPC.3
archiveHL7Application.hl7OrderMissingStudyIUIDPolicy.ACCESSION_BASED:Generate Study Instance UID based on Accession Number present in OBR.18 / IPC.1 if Study Instance UID missing in HL7 Order Messages in ZDS.1 / IPC.3
archiveHL7Application.hl7OrderMissingAdmissionIDPolicy:Политика HL7 налога без ID-а пријема|Специфицира политику за долазне HL7 Order поруке без вредности за PID-18 Patient Account Number нити поље PV1-19 Visit Number. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7OrderMissingAdmissionIDPolicy.ACCEPT:Accept HL7 Order Messages with missing Admission ID in PV1.19 / PID.18
archiveHL7Application.hl7OrderMissingAdmissionIDPolicy.REJECT:Reject HL7 Order Messages with missing Admission ID in PV1.19 / PID.18
archiveHL7Application.hl7OrderMissingAdmissionIDPolicy.ACCESSION_AS_ADMISSION:Use Accession Number present in OBR.18 / IPC.1 as Admission ID if it is missing in HL7 Order Message in PV1.19 / PID.18
archiveHL7Application.hl7MergeCompositeObjectMatchingKey:HL7 Merge Composite Object Matching Key|Specifies attribute of MWL to lookup already stored DICOM composite objects whose study and series attributes are updated with MWL attributes. Overwrites value specified on Device level.
archiveHL7Application.hl7MergeCompositeObjectMatchingKey.AccessionNumber:Use Accession Number (0008,0050) from MWL for matching composite objects
archiveHL7Application.hl7MergeCompositeObjectMatchingKey.StudyInstanceUID:Use Study Instance UID (0020,000D) from MWL for matching composite objects
archiveHL7Application.hl7ImportReportMissingStudyIUIDPolicy:Политика HL7 увоза извештаја без Study Instance UID-а|Специфицира политику за недостајући Study Instance UID у долазним HL7 Import Report (ORU) порукама. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ImportReportMissingStudyIUIDPolicy.REJECT:Reject HL7 ORU^R01 message with missing Study Instance UID in OBX.5 for OBX segment with OBX.3 as 'Study Instance UID' / 'DICOM Study'
archiveHL7Application.hl7ImportReportMissingStudyIUIDPolicy.GENERATE:Generate random Study Instance UID if it is missing in HL7 ORU^R01 Message in OBX.5 for OBX segment with OBX.3 as 'Study Instance UID' / 'DICOM Study'
archiveHL7Application.hl7ImportReportMissingStudyIUIDPolicy.ACCESSION_BASED:Generate Study Instance UID based on Accession Number present in OBR.18 if Study Instance UID missing in HL7 ORU^R01 Messages in OBX.5 for OBX segment with OBX.3 as 'Study Instance UID' / 'DICOM Study'
archiveHL7Application.hl7ImportReportMissingAdmissionIDPolicy:Политика HL7 увоза извештаја без ID-а пријема|Специфицира политику за долазне HL7 ImportReport (ORU) поруке без вредности за PID-18 Patient Account Number нити поље PV1-19 Visit Number. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ImportReportMissingAdmissionIDPolicy.ACCEPT:Accept HL7 ORU^R01 Messages with missing Admission ID in PV1.19 / PID.18
archiveHL7Application.hl7ImportReportMissingAdmissionIDPolicy.REJECT:Reject HL7 ORU^R01 Messages with missing Admission ID in PV1.19 / PID.18
archiveHL7Application.hl7ImportReportMissingAdmissionIDPolicy.ACCESSION_AS_ADMISSION:Use Accession Number present in OBR.18 as Admission ID if it is missing in HL7 ORU^R01 Message in PV1.19 / PID.18
archiveHL7Application.hl7ImportReportMissingStudyIUIDCFindSCP:C-FIND SCP за HL7 увоз извештаја без Study Instance UID-а|AE Title екстерног C-FIND SCP-а за упит за недостајући Study Instance UID у долазним HL7 Import Report (ORU) порукама по датом Accession Number-у. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ImportReportAdjustIUID:HL7 увоз извештаја прилагођава UID инстанце|Специфицира подешавање Series и SOP Instances UID-ова враћених од XSLT-а на долазним HL7 Import Report (ORU) порукама. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ImportReportAdjustIUID.NONE:No adjustment done to Study / Series / SOP IUIDs
archiveHL7Application.hl7ImportReportAdjustIUID.APPEND_HASH_OF_STUDY_INSTANCE_UID:Hash of Study Instance UID appended as suffix to Study / Series / SOP IUIDs
archiveHL7Application.hl7ReferredMergedPatientPolicy:Политика HL7 упућеног спојеног пацијента|Специфицира политику за долазне HL7 поруке које реферишу већ спојеног пацијента. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/HL7-Referred-Merged-Patient-Policy" target="_blank">значења HL7 Referred Merged Patient Policy</a>. Преписује вредност наведену на нивоу уређаја.
archiveHL7Application.hl7ReferredMergedPatientPolicy.REJECT:Reject any incoming HL7 messages referring an already merged Patient
archiveHL7Application.hl7ReferredMergedPatientPolicy.IGNORE:Ignore any incoming HL7 messages referring an already merged Patient
archiveHL7Application.hl7ReferredMergedPatientPolicy.IGNORE_DUPLICATE_MERGE:Ignore only duplicate incoming HL7 Patient Merge (ADT^A40) messages referring an already merged Patient. Reject any other incoming HL7 messages referring an already merged Patient.
archiveHL7Application.hl7ReferredMergedPatientPolicy.ACCEPT_INVERSE_MERGE:Accept any incoming inverse HL7 Patient Merge (ADT^A40) messages referring an already merged Patient, optionally allowing inverse merging of patient records if clients send duplicated ADT^A40 patient merge messages repeatedly, just reversing the patient identifier values in PID / MRG segments.
archiveHL7Application.hl7DicomCharacterSet:HL7 DICOM скуп знакова|Указује на коришћење наведене вредности Specific Character Set (0008,0005) у Data Sets транскодираним из примљених HL7 порука. Користи вредност која одговара Character Set-у HL7 поруке наведеном у MSH-18 ако није наведено.
archiveHL7Application.hl7ForwardRule:HL7 правило прослеђивања|HL7 Forward правило. Допуњује вредности наведене на нивоу уређаја.
archiveHL7Application.hl7ExportRule:HL7 правило извоза|Export правила примењена на HL7 поруке примљене од ове HL7 апликације. Допуњује HL7 Export Rules наведене на нивоу уређаја.
archiveHL7Application.hl7UPSOnHL7:UPS правила на HL7|UPS on HL7 правила примењена на HL7 поруке примљене од било које HL7 апликације. Допуњује UPS on HL7 Rules наведене на нивоу уређаја.
archiveHL7Application.hl7PrefetchRule:HL7 правило предузимања|Префетцх правила примењена на HL7 поруке примљене од ове HL7 апликације. Допуњује HL7 Prefetch Rules наведене на нивоу уређаја.
archiveHL7Application.hl7StudyRetentionPolicy:HL7 политика задржавања студије|HL7 Study Retention политике окинуте HL7 порукама примљеним од ове HL7 апликације. Допуњује вредности наведене на нивоу уређаја.
archiveHL7Application.hl7OrderScheduledStation:Заказана станица за HL7 налог|Scheduled Station селектована на MWL HL7 Order Feed-у. Допуњује вредности наведене на нивоу уређаја.
archiveHL7Application.hl7OrderSPSStatus:SPS status за HL7 налог|Специфицира SPS Status DICOM MWL ставки креираних/ажурираних на примљеним HL7 ORM^O01, OMI^O23, OMG^O19 порукама. Преписује вредности наведене на нивоу уређаја.
