archiveAttributeCoercion:Архивско цоерцион атрибута - Legacy|Архивско цоерцион атрибута примљених/послатих DIMSE
archiveAttributeCoercion.cn:Име|Произвољно/Смислено име архивског цоерцион-а атрибута
archiveAttributeCoercion.dcmRulePriority:Приоритет правила|Ако се стање више арцхиве аттрибуте цоерцион (legacy) подудара за примљену слику, примењује се цоерцион вишег приоритета. Ако постоји више подударних цоерцион-а са једнаким приоритетом, недефинисано је која се цоерцион примењује.
archiveAttributeCoercion.dcmDIMSE:DIMSE|DICOM Message Element на који се ова Attribute Coercion примењује. Такође <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Legacy-Archive-Attribute-Coercion---Application-of-multiple-coercions-using-one-coercion-rule#dimse" target="_blank">примењиво ако се захтеви примају преко web-а.</a>
archiveAttributeCoercion.dicomTransferRole:DICOM улога преноса|DICOM улога преноса пеер DICOM AE-а.
archiveAttributeCoercion.dcmSOPClass:SOP Class UID|UID SOP класе за коју се овај цоерцион атрибута примењује. Ако недостаје, примењује се на било коју.
archiveAttributeCoercion.dcmProperty:Услови|Услови у формату {key}[!]={value}. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Conditions" target="_blank">применљивост, формат и примере.</a>
archiveAttributeCoercion.dcmRetrieveAsReceived:Преузми као примљено|Онемогућава спајање DB информација у преузети Composite Object, враћајући објекте као примљене. Ефикасно само са DIMSE = C_STORE_RQ и DICOM Transfer Role = SCP.
archiveAttributeCoercion.dcmDeIdentification:Де-идентификација|Де-идентификуј објекте према Basic Application Level Confidentiality Profile специфицираном у DICOM PS3.15. Бирањем било које опције имплицитно се укључује Basic Application Level Confidentiality Profile.
archiveAttributeCoercion.dcmURI:URI XSL стилног листа|Специфицира URI XSL style схеет-а за Attribute Coercion
archiveAttributeCoercion.dcmNoKeywords:Без кључне речи атрибута|Указује да ли да кључне речи атрибута буду изостављене из DICOM XML прослеђеног XSLT-у
archiveAttributeCoercion.dcmMergeMWLMatchingKey:Кључ подударања спајања MWL|Специфицира атрибут примљеног објекта за проналажење MWL ставке коришћене за коерцију атрибута захтева. Ако није наведено, атрибути захтева примљених објеката се неће коирцирати. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Legacy-Archive-Attribute-Coercion---Application-of-multiple-coercions-using-one-coercion-rule#configurations-specific-to-merging-from-mwl-coercion-type" target="_blank">применљивост мерге MWL матцхинг кључева.</a>
archiveAttributeCoercion.dcmMergeMWLTemplateURI:URI шаблона спајања MWL|Специфицира URI style схеет-а за коерцију атрибута захтева примљених објеката из подударних DICOM MWL ставки. Ефикасно само ако је наведен dcmMergeMWLMatchingKey.
archiveAttributeCoercion.dcmMergeMWLSCP:SCP спајања MWL|AE Title екстерног MWL SCP-а коришћеног за проналажење MWL ставке за коерцију атрибута захтева примљених објеката. Ако је конфигурисано, екстерни MWL SCP се упитује позивањем C-FIND RQ-а DICOM MWL услуге и Мерге Local MWL SCP се игнорише.
archiveAttributeCoercion.dcmMergeLocalMWLWorklistLabel:Ознака локалне MWL Worklist-е за спајање|Разматрај само MWL ставке са једном од наведених вредности његовог Worklist Label (0074,1202) у Archive DB за коерцију атрибута захтева примљених објеката. Ако није наведено, Archive DB се упитује за подударање MWL ставки са било којим Worklist Label (0074,1202).
archiveAttributeCoercion.dcmMergeLocalMWLWithStatus:Споји локални MWL са статусом|Разматрај само MWL ставке са једним од наведених Scheduled Procedure Step Status кодова. Ако није наведено, разматрају се MWL ставке са било којим Scheduled Procedure Step Status-ом.
archiveAttributeCoercion.dcmMWLImportFilterBySCU:Филтер спајања MWL по SCU|Означава да се наведени филтер примењује на подударања која врати екстерни MWL SCP.
archiveAttributeCoercion.dcmLeadingCFindSCP:Водећи C-FIND SCP|AE Title екстерног C-FIND SCP-а за Attribute Coercion са атрибутима пацијента и студије дохваћеним са овог AE-а. Ако није наведен појединачни Attribute Set за C-FIND SCP, дохватит ће се сви атрибути конфигурисаног Patient и Study Attribute Filter-а.
archiveAttributeCoercion.dcmAttributeUpdatePolicy:Политика ажурирања атрибута|Специфицира како атрибути треба да буду ажурирани атрибутима дохваћеним са Leading C-FIND SCP-а. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Attribute-Update-Policy" target="_blank">значења Attribute Update Policies.</a>
archiveAttributeCoercion.dcmTrimISO2022CharacterSet:Скрати ISO 2022 скуп знакова|Замени појединачни код за Сингле-Byte Character Sets са Code Extensions кодом за Сингле-Byte Character Sets без Code Extensions. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Legacy-Archive-Attribute-Coercion---Application-of-multiple-coercions-using-one-coercion-rule#configurations-specific-to-trim-iso-2022-character-set-coercion-type" target="_blank">карактерне скупове на које се ова цоерцион примењује.</a>
archiveAttributeCoercion.dcmUseCallingAETitleAs:Користи позивајући AE наслов као|Идентификује атрибут који се поставља на вредност Calling AET-а ако је одсутан или празан. ScheduledStationAETitle (= Scheduled Station AE Title (0040,0001) у ставци Scheduled Procedure Step Sequence (0040,0100)), SendingApplicationEntityTitleOfSeries (= Sending Application Entity Title of Series (7777,xx37)).
archiveAttributeCoercion.dcmNullifyTag:Поништи ознаку атрибута|DICOM ознака атрибута који треба нуллификовати као хексадецимални стринг
archiveAttributeCoercion.dcmMergeAttribute:Споји атрибут|Merge DICOM атрибут у формату {attributeID}={value}. {attributeID} унутар {value} ће бити замењено вредношћу тог атрибута у оригиналном датасет-у. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Legacy-Archive-Attribute-Coercion---Application-of-multiple-coercions-using-one-coercion-rule#configurations-specific-to-merge-attributes-coercion-type" target="_blank">применљивост, формате и неке примере.</a>
archiveAttributeCoercion.dcmNullifyIssuerOfPatientID:Поништи издаваоца ID-а пацијента|Условно нуллификуј Issuer of Patient ID (0010,0021) и Issuer of Patient ID Qualifiers Sequence (0010,0024) из примљених објеката
archiveAttributeCoercion.dcmIssuerOfPatientID:Издавалац ID-а пацијента|Issuer of Patient ID (0010,0021) и опционално и вредности за Universal Entity ID (0040,0032) и Universal Entity ID Type (0040,0033) ставке Issuer of Patient ID Qualifiers Sequence (0010,0024) се пореде са вредностима у примљеним објектима, ако је Nullify Issuer of Patient ID постављено на MATCHING или NOT_MATCHING. Наведите вредности у формату: {IssuerOfPatientID}[&{UniversalEntityID&UniversalEntityIDType}].
archiveAttributeCoercion.dcmIssuerOfPatientIDFormat:Формат издаваоца ID-а пацијента|Формат Issuer of Patient ID (0010,0021) изведен из других атрибута. Нпр. "{00100010,hash}-{00100030}": користи хасх вредност Patient Name и Birth Date раздвојене са "-". Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Legacy-Archive-Attribute-Coercion---Application-of-multiple-coercions-using-one-coercion-rule#configurations-specific-to-supplement-issuer-of-patient-id-format-coercion-type" target="_blank">применљивост овог поља и неке примере.</a>
archiveAttributeCoercion.dcmSupplementFromDeviceReference:Допуни из уређаја|Име уређаја са којег се допуњују Assigning Authorities и друге информације. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Legacy-Archive-Attribute-Coercion---Application-of-multiple-coercions-using-one-coercion-rule#configurations-specific-to-supplementing-from-device-coercion-type" target="_blank">применљивост на ентитете и информације допуњене са уређаја.</a>
