attributeFilter:Филтер атрибута|Атрибути ускладиштени у бази података
attributeFilter.dcmEntity:Ентитет атрибута|Ентитет Attribute Filter-а или Export правила ('Patient', 'Study', 'Series', 'Instance', 'MPPS', 'MWL', 'UPS').
attributeFilter.dcmTag:Ознака атрибута|DICOM ознака као хексадецимални стринг
attributeFilter.dcmCustomAttribute1:Произвољни атрибут 1|Конфигуриши било који атрибут из DICOM објекта који треба да буде уметнут у базу података као Custom Attribute 1. Примјењиво само за Patient / Study / Series / Instance ентитете. Нпр. DicomAttribute[@tag="00200070"]/Валуе[@number="1"] или за Привате атрибут DicomAttribute[@tag="00E10024" and @privateCreator="ELSCINT1"]/Валуе[@number="1"]
attributeFilter.dcmCustomAttribute2:Произвољни атрибут 2|Конфигуриши било који атрибут из DICOM објекта који треба да буде уметнут у базу података као Custom Attribute 2. Примјењиво само за Patient / Study / Series / Instance ентитете. Нпр. DicomAttribute[@tag="00200070"]/Валуе[@number="1"] или за Привате атрибут DicomAttribute[@tag="00E10024" and @privateCreator="ELSCINT1"]/Валуе[@number="1"]
attributeFilter.dcmCustomAttribute3:Произвољни атрибут 3|Конфигуриши било који атрибут из DICOM објекта који треба да буде уметнут у базу података као Custom Attribute 3. Примјењиво само за Patient / Study / Series / Instance ентитете. Нпр. DicomAttribute[@tag="00200070"]/Валуе[@number="1"] или за Привате атрибут DicomAttribute[@tag="00E10024" and @privateCreator="ELSCINT1"]/Валуе[@number="1"]
attributeFilter.dcmAttributeUpdatePolicy:Политика ажурирања атрибута|Специфицира политику ажурирања за екстрактоване атрибуте у DB на нивоу Series, Study & Patient при пријему даљих инстанци ентитета.
attributeFilter.dcmAttributeUpdatePolicy.PRESERVE:The attributes will be preserved. Nullify attributes in the new dataset which are not present in the original dataset. Any extra attributes will be nullified
attributeFilter.dcmAttributeUpdatePolicy.SUPPLEMENT:The attributes will be overwritten. Attributes not present in original dataset will be supplemented. Any extra attributes with not null values will be added
attributeFilter.dcmAttributeUpdatePolicy.MERGE:The attributes will be overwritten. Attribute values will be written from new dataset. Any attributes with not null values, shall not be overwritten by attributes with null values
attributeFilter.dcmAttributeUpdatePolicy.OVERWRITE:The attributes will be overwritten. Attribute values if null in new dataset, will be nullified in original dataset. Any attributes with not null values, shall be overwritten by attributes with null values
attributeFilter.dcmAttributeUpdatePolicy.REPLACE:The attributes will be completely overwritten
