changeAccessControlIDRule:Правило промене ID-а контроле приступа|Change Access Control ID правило
changeAccessControlIDRule.cn:Име|Произвољно/Смислено име Change Access Control ID правила
changeAccessControlIDRule.dicomAETitle:Наслов архивског апликационог ентитета (AE)|Титле Archive Application Entity (AE) чији конфигурисани Query Retrieve View и Access Control ID се примењују при избору Студиес или Series чијем додељеном Access Control ID треба променити.
changeAccessControlIDRule.dcmStoreAccessControlID:ID контроле приступа складишту|Нови Access Control ID додељен селектованим студијама или појединачним серијама након наведеног кашњења након пријема првог објекта студије. '*' уклања претходно додељени Access Control ID, чинећи студију или серију доступном на свим Арцхиве AE-овима.
changeAccessControlIDRule.dcmAccessControlID:ID контроле приступа|Претходни Access Control ID-ови додељени селектованим студијама или појединачним серијама за промену. Ако није наведена вредност, сви Access Control ID-ови доступни од стране наведеног Archive Application Entity (AE) ће бити промењени.
changeAccessControlIDRule.dcmEntity:Ентитет|Указује да ли Access Control ID додељен студијама или појединачним серијама треба бити промењен.
changeAccessControlIDRule.dcmEntitySelector:Бирач ентитета|Специфицира кључеве подударања коришћене за селекцију примљених студија или серија чији Access Control ID треба да буде ажуриран. Формат: {key}={value}[&{key}={value}]..., са {key} = {attributeID}. Ако није наведен Entity Selector, Accession Control ID-ови свих студија или серија видљивих за наведени Archive AE ће бити ажурирани на наведени Store Access Control ID.
changeAccessControlIDRule.dcmChangeAccessControlIDDelay:Кашњење промене ID-а контроле приступа|Кашњење након пријема првог објекта студије/серије након којег ће се Access Control ID повезан са студијом или укључујућом серијом променити у наведени Store Access Control ID у ISO-8601 формату трајања PnDTnHnMn.nS.
changeAccessControlIDRule.dcmChangeAccessControlIDMaxDelay:Максимално кашњење промене ID-а контроле приступа|Указује на престанак примене овог правила за студије/серије чији је први објекат примљен пре наведеног интервала у ISO-8601 формату трајања PnDTnHnMn.nS. Обавезно ако постоје друга правила за поновну промену Access Control ID-а у будућности.
