pdqService:PDQ сервис|Дескриптор сервиса упита демографских података пацијената
pdqService.dcmPDQServiceID:ID PDQ сервиса|Patient Demographics Query Service ID
pdqService.dcmURI:URI сервиса упита демографских података пацијената|PDQ Service URI, нпр. 'pdq-dicom:FINDSCP' или 'pdq-hl7:SendingApplication/SendingFacility:ReceivingApplication/ReceivingFacility' или pdq-фхир:HL7-FHIR-R4-WebApplication.
pdqService.dicomDescription:Опис PDQ сервиса|Неспутани текстуални опис Patient Demographics Query Service
pdqService.dcmTag:Атрибути пацијента|Атрибути пацијента који се упитују - ако није наведено, упитаће се сви доступни атрибути пацијента. Примјењиво само за 'pdq-dicom' PDQ услугу
pdqService.dcmEntity:Ентитет упита|Указује да ли се C-FIND SCP упитује за појединог пацијента или за студије појединог пацијента. Ефикасно само за DICOM PDQ услуге (URI: pdq-дицом:{AETitle}).
pdqService.dcmProperty:Својство PDQ сервиса|Својство у формату <name>=<value>, нпр. 'LocalAET=DCM4CHEE' за URI са шемом pdq-дицом или 'XSLStylesheetURI=${jboss.server.temp.url}/dcm4chee-arc/hl7-adt2dcm.xsl' за URI са шемом pdq-хл7 или 'XSLStylesheetURI=${jboss.server.temp.url}/dcm4chee-arc/fhir-pat2dcm.xsl' за URI са шемом pdq-фхир. Додатна својства за URI са шемом pdq-фхир могу се поставити нпр. 'search._format=xml', 'search.identifier.system={issuer}'. За комплетну листу својстава, погледајте https://github.com/dcm4che/dcm4chee-arc-light/issues/3307
