queue:Ред|Управљани ред задатака
queue.dcmQueueName:Име реда|Име реда задатака
queue.dicomInstalled:инсталиран|Ако је нетачно, обрада задатаака у овом реду је паузирана.
queue.dcmMaxTasksParallel:Максимално паралелних задатака|Максималан број таск-ова обрађених паралелно.
queue.dicomDescription:DICOM опис|Текстуални опис DICOM ентитета
queue.dcmMaxRetries:Максималан број поновних покушаја|Максималан број покушаја обраде задатака заказаних у специфичном реду.
queue.dcmRetryDelay:Кашњење поновног покушаја|Кашњење поновног покушаја обраде задатаака планираних у поједином реду у ISO-8601 формату трајања PnDTnHnMn.nS.
queue.dcmMaxRetryDelay:Максимално кашњење поновног покушаја|Максимално кашњење поновног покушаја обраде задатака планираних у поједином реду у ISO-8601 формату трајања PnDTnHnMn.nS. Бесконачно ако није наведено.
queue.dcmRetryDelayMultiplier:Множилац кашњења поновног покушаја|Мултипликатор у % који ће се применити на врху dcmRetryDelay са dcmMaxRetryDelay који се узима у обзир.
queue.dcmRetryOnWarning:Понови при упозорењу|Омогућава поновне покушаје обраде задатаака не само при неуспеху већ и при warning статусу исхода у поједином реду.
queue.dcmPurgeQueueMessageCompletedDelay:Кашњење брисања завршених задатака|Кашњење у ISO-8601 формату трајања PnDTnHnMn.nS након којег се завршени задаци прочишћавају. Ако није наведено, нема брисања за тај поједини ред
queue.dcmPurgeQueueMessageFailedDelay:Кашњење брисања неуспелих задатака|Кашњење у ISO-8601 формату трајања PnDTnHnMn.nS након којег се неуспели задаци прочишћавају. Ако није наведено, нема брисања за тај поједини ред
queue.dcmPurgeQueueMessageWarningDelay:Кашњење брисања задатака са упозорењем|Кашњење у ISO-8601 формату трајања PnDTnHnMn.nS након којег се задаци са упозорењем прочишћавају. Ако није наведено, нема брисања за тај поједини ред
queue.dcmPurgeQueueMessageCanceledDelay:Кашњење брисања отказаних задатака|Кашњење у ISO-8601 формату трајања PnDTnHnMn.nS након којег се отказани задаци прочишћавају. Ако није наведено, нема брисања за тај поједини ред
queue.dcmSchedule:Ограничи заказивање|Ограничи планирање на наведене временске опсеге.
