uiAet:Падајућа листа AET-ова|Падајућа листа AET
uiAet.dcmuiAetListName:Име листе|Дефинишите име за ову конфигурацију
uiAet.dcmuiAetListDescription:Опис|Опис AET листе
uiAet.dcmuiMode:Режим листе AET-ова|Дефиниши у ком моду треба да буде ова конфигурација доступна у 'internal' ( арцхиве сопствени AET-ови, на неким местима такође звани 'Home AET' или 'Local AET' ) или 'external' ( или на неким местима такође звани 'Remote AET' ) ает падајућој листи, да би била доступна за оба немојте селектовати ниједан
uiAet.dcmuiAets:AET-ови|Параметар UI акције
uiAet.dcmAcceptedUserRole:Прихваћена корисничка улога|Дефиниши улоге за које ова конфигурација треба да буде доступна, користи 'user' да буде доступна за све улоге
