uiPermission:UI дозвола|UI дозвола
uiPermission.dcmuiPermissionName:Име UI дозволе|Име дозволе за UI акцију
uiPermission.dcmuiAction:UI акција|UI акција
uiPermission.dcmuiActionParam:Параметар UI акције|Параметар UI акције
uiPermission.dcmAcceptedUserRole:Прихваћена корисничка улога|Прихваћена корисничка улога
