uiTable:Конфигурација UI табеле|Конфигурација Study табеле за про верзију
uiTable.dcmuiTableConfigName:Име конфигурације|Име UI Table конфигурације
uiTable.dcmuiTableConfigUsername:Корисничко име|Корисничко име којем овај скуп треба бити доступан
uiTable.dcmuiTableConfigRoles:Улога|Корисничка улога која може користити овај скуп (Ако поставите корисничко име, улога ће бити игнорисана)
uiTable.dcmuiTableID:ID табеле|ID табеле у UI-ју за коју конфигурација треба да буде на снази
uiTable.dcmuiTableConfigIsDefault:Подразумевано|Постави овај Цолумн-Сет као подразумевани. (Уверите се да је само један од Сет - сиблингс цхилд постављен као подразумевани).
uiTable.dcmuiTableColumnConfigObjects:Колоне табеле|Дефиниши колоне табеле
