uiWebApp:Падајућа листа веб апликација|Падајућа листа Web App
uiWebApp.dcmuiWebAppListName:Име листе|Дефинишите име за ову конфигурацију
uiWebApp.dcmuiWebAppListDescription:Опис|Опис листе Web апликација
uiWebApp.dcmuiMode:Режим листе|Имате две могућности како да прикажете дефинисану листу: 1.) На врху изнад остатка листе 'separated' са линијом, 2.) Прикажи само овде дефинисане ( 'exclusive' ).
uiWebApp.dcmuiWebApps:Веб апликације|Веб апликација
uiWebApp.dcmAcceptedUserRole:Прихваћена корисничка улога|Дефиниши улоге за које ова конфигурација треба да буде доступна, користи 'user' да буде доступна за све улоге ( Треба да дефинишете или корисничко име ( следећи атрибут ) или корисничку улогу ( овај атрибут ))
uiWebApp.dcmAcceptedUserName:Прихваћено корисничко име|Дефиниши корисничко име за које ова конфигурација треба да буде доступна ( Треба да дефинишете или корисничко име ( овај атрибут ) или корисничку улогу ( претходни атрибут ))
