upsOnStore:UPS на складиштење|Креирај/Ажурирај Workitem у обједињеној Worklist при пријему Composite Object-а
upsOnStore.dcmUPSOnStoreID:ID UPS-а на складиштење|ID UPS on Store правила
upsOnStore.dcmProperty:Услови|Услови у формату {key}[!]={value}. Погледајте <a href="https://github.com/dcm4che/dcm4chee-arc-light/wiki/Conditions" target="_blank">применљивост, формат и примере.</a>
upsOnStore.dcmSchedule:Временски услови|Примени ово правило само у наведеним временским опсезима.
upsOnStore.dcmUPSLabel:Ознака корака процедуре|Вредност Procedure Step Label (0074,1204) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {StudyDescription}
upsOnStore.dcmUPSWorklistLabel:Ознака Worklist-е|Вредност Worklist Label (0074,1202) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {StudyDescription}
upsOnStore.dcmUPSPriority:Приоритет|Вредност Scheduled Procedure Step Priority (0074,1200) у креираном UPS-у.
upsOnStore.dcmUPSInputReadinessState:Стање спремности уноса|Вредност Input Readiness State (0040,4041) у креираном UPS-у
upsOnStore.dcmUPSStartDateTimeDelay:Кашњење датума/времена почетка заказаног корака процедуре|Кашњење Scheduled Procedure Step Start DateTime (0040,4005) у креираном UPS-у од времена пријема у формату PnDTnHnMn.nS. Без кашњења ако није наведено.
upsOnStore.dcmUPSCompletionDateTimeDelay:Кашњење очекиваног датума/времена завршетка|Кашњење Expected Completion DateTime (0040,4011) у креираном UPS-у од времена пријема у формату PnDTnHnMn.nS. Ако није наведено, неће се поставити Expected Completion Date и Тиме.
upsOnStore.dcmUPSInstanceUIDBasedOnName:UID UPS instance на основу имена|Вредност која се користи за генерисање наме басед SOP Instance UID (0008,0018) у креираном UPS-у. Типично ће вредност укључивати {StudyInstanceUID}, {SeriesInstanceUID} или {SOPInstanceUID} да би се креирао различит UPS за сваки примљени Study, Series или Object. Ако није наведено, користиће се рандом генерисан SOP Instance UID (0008,0018).
upsOnStore.dcmUPSIncludeInputInformation:Укључи улазне информације|Указује да ли примљени објекти треба да буду референцирани у Input Information Sequence (0040,4021) креираног UPS-а.
upsOnStore.dcmUPSIncludeInputInformation.NO:Do not include Input Information Sequence
upsOnStore.dcmUPSIncludeInputInformation.SINGLE:Do not updating existing UPS
upsOnStore.dcmUPSIncludeInputInformation.APPEND:Update existing UPS in state SCHEDULED
upsOnStore.dcmUPSIncludeInputInformation.SINGLE_OR_CREATE:If UPS already exists, create new UPS with derived UID
upsOnStore.dcmUPSIncludeInputInformation.APPEND_OR_CREATE:If existing UPS is no longer in state SCHEDULED, create new UPS with derived UID
upsOnStore.dcmUPSIncludePatient:UPS укључи пацијента|Указује да ли је пацијент (повезан са креираним UPS) креиран коришћењем атрибута пацијента у примљеном објекту; тачно ако није наведено.
upsOnStore.dcmDestinationAE:Одредишни AE|Наслов DICOM апликационог ентитета у који ће инстанце бити сачуване.
upsOnStore.dcmEntity:Обим акумулације|Обим акумулације
upsOnStore.dcmUPSScheduledWorkitemCode:Код заказаног Workitem-а|Ставка секвенце кода заказаног Workitem-а (0040,4018) у креираном UPS-у у формату (CV, CSD, "CM").
upsOnStore.dcmUPSScheduledStationNameCode:Код имена заказане станице|Ставка секвенце кода имена заказане станице (0040,4025) у креираном UPS-у у формату (CV, CSD, "CM").
upsOnStore.dcmUPSScheduledStationClassCode:Код класе заказане станице|Ставка секвенце кода класе заказане станице (0040,4026) у креираном UPS-у у формату (CV, CSD, "CM").
upsOnStore.dcmUPSScheduledStationLocationCode:Код географске локације заказане станице|Ставка секвенце кода географске локације заказане станице (0040,4027) у креираном UPS-у у формату (CV, CSD, "CM").
upsOnStore.dcmUPSScheduledHumanPerformerCode:Код заказаног људског извршиоца|Ставка Human Performer Code Sequence (0040,4009) у ставци Scheduled Human Performers Sequence (0040,4034) у креираном UPS-у у формату (CV, CSD, "CM").
upsOnStore.dcmUPSScheduledHumanPerformerName:Име заказаног људског извршиоца|Вредност Human Performer's Name (0040,4037) у ставци Scheduled Human Performers Sequence (0040,4034) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {PerformingPhysicianName}
upsOnStore.dcmUPSScheduledHumanPerformerOrganization:Организација заказаног људског извршиоца|Вредност Human Performer's Organization (0040,4036) у ставци Scheduled Human Performers Sequence (0040,4034) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {ResponsibleOrganization}
upsOnStore.dcmAdmissionID:Број пријема|Вредност Admission ID (0038,0010) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {AdmissionID}
upsOnStore.dicomIssuerOfAdmissionID:Издавалац ID-а пријема|Вредност Local Namespace Entity ID (0040,0031), Universal Entity ID (0040,0032) и Universal Entity ID Type (0040,0033) ставке Issuer of Admission ID Sequence (0038,0014) у креираном UPS-у. Формат: &лт;Local Namespace Entity ID&гт;['&'&lt;Universal Entity ID&gt;'&'&lt;Universal Entity ID Type&gt;]
upsOnStore.dcmUPSIncludeStudyInstanceUID:Укључи Study Instance UID|Указује да ли Study Instance UID (0020,000D) примљеног објекта треба бити укључен у креирани UPS
upsOnStore.dcmUPSIncludeReferencedRequest:Укључи референцирани захтев|Указује да ли ће Study Instance UID (0020,000D) примљеног објекта и наведени Accession Number (0008,0050), Requested Procedure ID (0040,1001) и Requesting Service (0032,1033) бити укључени у ставку Referenced Request Sequence (0040,A370) у креираном UPS-у. У супротном, укључује се празна Referenced Request Sequence (0040,A370).
upsOnStore.dcmAccessionNumber:Приступни број|Вредност Accession Number (0008,0050) у ставци Referenced Request Sequence (0040,A370) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {AccessionNumber}
upsOnStore.dicomIssuerOfAccessionNumber:Издавалац приступног броја|Вредност Local Namespace Entity ID (0040,0031), Universal Entity ID (0040,0032) и Universal Entity ID Type (0040,0033) у ставки Issuer of Accession Number Sequence (0008,0051) у ставци Referenced Request Sequence (0040,A370) у креираном UPS-у. Формат: &лт;Local Namespace Entity ID&гт;['&'&lt;Universal Entity ID&gt;'&'&lt;Universal Entity ID Type&gt;]
upsOnStore.dcmRequestedProcedureID:ID траженог поступка|Вредност Requested Procedure ID (0040,1001) у ставци Referenced Request Sequence (0040,A370) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {StudyID}
upsOnStore.dcmRequestedProcedureDescription:Опис траженог поступка|Вредност Requested Procedure Description (0032,1060) у ставци Referenced Request Sequence (0040,A370) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {StudyDescription}
upsOnStore.dcmRequestedProcedureCode:Requested Procedure Code Sequence|Value of Code Value (0008,0100), Coding Scheme Designator (0008,0102) and Code Meaning (0008,0104) in Item of Requested Procedure Code Sequence (0032,1064) in Item of Referenced Request Sequence (0040,A370) in created UPS. Format: (&lt;CodeValue&gt;, &lt;CodingSchemeDesignator&gt;, "&lt;CodeMeaning&gt;")
upsOnStore.dcmRequestingPhysician:Лекар који тражи|Вредност Requesting Physician (0032,1032) у ставци Referenced Request Sequence (0040,A370) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {PerformingPhysicianName}
upsOnStore.dcmRequestingService:Сервис који тражи|Вредност Requesting Service (0032,1033) у ставци Referenced Request Sequence (0040,A370) у креираном UPS-у. {attributeID} ће бити замењено вредношћу тог атрибута у примљеном датасету. Пример: {StudyDescription}
upsOnStore.dcmURI:URI XSL стилног листа|Специфицира URI XSL style схеет-а за укључивање додатних атрибута у креирани UPS.
upsOnStore.dcmNoKeywords:Без кључне речи атрибута|Означава да ли кључне речи атрибута треба изоставити у DICOM XML прослеђеном XSLT-у.
